using System;
using System.Collections.Generic;

namespace Wc3o {
	public class BuildingInfo : EntityInfo {

		#region " Get "
		static SortedDictionary<BuildingType, BuildingInfo> infos;
		public static BuildingInfo Get(BuildingType t) {
			if (infos == null)
				infos = new SortedDictionary<BuildingType, BuildingInfo>();
			if (!infos.ContainsKey(t))
				Create(t);
			return infos[t];
		}
		#endregion

		#region " Create "
		static void Create(BuildingType t) {
			BuildingInfo i = new BuildingInfo();
			i.type = t;

			i.bonusAuraArmor = 1;
			i.malusAuraArmor = 1;
			i.bonusAuraRange = 1;
			i.malusAuraRange = 1;
			i.bonusAuraHitpoints = 1;
			i.malusAuraHitpoints = 1;
			i.bonusAuraAttackGround = 1;
			i.malusAuraAttackGround = 1;
			i.bonusAuraAttackAir = 1;
			i.malusAuraAttackAir = 1;
			i.bonusAuraCooldown = 1;
			i.malusAuraCooldown = 1;
			i.buildable = true;

			switch (t) {
				case BuildingType.GreatHall:
					i.fraction = Fraction.Orcs;
					i.name = "Great Hall";
					i.image = "/Orcs/GreatHall.gif";
					i.createImage = "/Orcs/GreatHall.gif";
					i.gold = 385;
					i.lumber = 185;
					i.hitpoints = 1500;
					i.minutes = 450;
					i.armor = 5;
					i.armorType = ArmorType.Fort;
					i.attackTypeAir = AttackType.None;
					i.attackTypeGround = AttackType.None;
					i.attackAir = 0;
					i.attackGround = 0;
					i.cooldown = 0;
					i.range = 0;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[1];
					i.upgradesTo[0] = BuildingType.Stronghold;
					i.requirements = new BuildingType[0];
					i.score = 3;
					i.number = 3;
					i.numberPerSector = 1;
					i.food = 10;
					break;
				case BuildingType.Stronghold:
					i.fraction = Fraction.Orcs;
					i.name = "Stronghold";
					i.image = "/Orcs/Stronghold.gif";
					i.createImage = "/Orcs/Stronghold.gif";
					i.gold = 315;
					i.lumber = 190;
					i.hitpoints = 1600;
					i.minutes = 420;
					i.armor = 5;
					i.armorType = ArmorType.Fort;
					i.attackTypeAir = AttackType.None;
					i.attackTypeGround = AttackType.None;
					i.attackAir = 0;
					i.attackGround = 0;
					i.cooldown = 0;
					i.range = 0;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[1];
					i.upgradesTo[0] = BuildingType.Fortress;
					i.requirements = new BuildingType[0];
					i.score = 7;
					i.number = 2;
					i.numberPerSector = 1;
					i.food = 10;
					i.buildable = false;
					break;
				case BuildingType.Fortress:
					i.fraction = Fraction.Orcs;
					i.name = "Fortress";
					i.image = "/Orcs/Fortress.gif";
					i.createImage = "/Orcs/Fortress.gif";
					i.gold = 325;
					i.lumber = 190;
					i.hitpoints = 1800;
					i.minutes = 420;
					i.armor = 5;
					i.armorType = ArmorType.Fort;
					i.attackTypeAir = AttackType.None;
					i.attackTypeGround = AttackType.None;
					i.attackAir = 0;
					i.attackGround = 0;
					i.cooldown = 0;
					i.range = 0;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[0];
					i.requirements = new BuildingType[1];
					i.requirements[0] = BuildingType.AltarOfStorms;
					i.score = 10;
					i.number = 1;
					i.numberPerSector = 1;
					i.food = 10;
					i.buildable = false;
					break;
				case BuildingType.OrcBarracks:
					i.fraction = Fraction.Orcs;
					i.name = "Barracks";
					i.image = "/Orcs/Barracks.gif";
					i.createImage = "/Orcs/Barracks.gif";
					i.gold = 180;
					i.lumber = 50;
					i.hitpoints = 1200;
					i.minutes = 180;
					i.armor = 5;
					i.armorType = ArmorType.Fort;
					i.attackTypeAir = AttackType.None;
					i.attackTypeGround = AttackType.None;
					i.attackAir = 0;
					i.attackGround = 0;
					i.cooldown = 0;
					i.range = 0;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[0];
					i.requirements = new BuildingType[0];
					i.score = 4;
					i.number = 2;
					i.numberPerSector = 1;
					break;
				case BuildingType.AltarOfStorms:
					i.fraction = Fraction.Orcs;
					i.name = "Altar Of Storms";
					i.image = "/Orcs/AltarOfStorms.gif";
					i.createImage = "/Orcs/AltarOfStorms.gif";
					i.gold = 180;
					i.lumber = 50;
					i.hitpoints = 900;
					i.minutes = 180;
					i.armor = 5;
					i.armorType = ArmorType.Fort;
					i.attackTypeAir = AttackType.None;
					i.attackTypeGround = AttackType.None;
					i.attackAir = 0;
					i.attackGround = 0;
					i.cooldown = 0;
					i.range = 0;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[0];
					i.requirements = new BuildingType[0];
					i.score = 5;
					i.number = 2;
					i.numberPerSector = 1;
					break;
				case BuildingType.WarMill:
					i.fraction = Fraction.Orcs;
					i.name = "War Mill";
					i.image = "/Orcs/WarMill.gif";
					i.createImage = "/Orcs/WarMill.gif";
					i.gold = 205;
					i.lumber = 0;
					i.hitpoints = 1000;
					i.minutes = 210;
					i.armor = 5;
					i.armorType = ArmorType.Fort;
					i.attackTypeAir = AttackType.None;
					i.attackTypeGround = AttackType.None;
					i.attackAir = 0;
					i.attackGround = 0;
					i.cooldown = 0;
					i.range = 0;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[0];
					i.requirements = new BuildingType[0];
					i.score = 4;
					i.number = 2;
					i.numberPerSector = 1;
					break;
				case BuildingType.Beastiary:
					i.fraction = Fraction.Orcs;
					i.name = "Beastiary";
					i.image = "/Orcs/Beastiary.gif";
					i.createImage = "/Orcs/Beastiary.gif";
					i.gold = 145;
					i.lumber = 140;
					i.hitpoints = 1100;
					i.minutes = 180;
					i.armor = 5;
					i.armorType = ArmorType.Fort;
					i.attackTypeAir = AttackType.None;
					i.attackTypeGround = AttackType.None;
					i.attackAir = 0;
					i.attackGround = 0;
					i.cooldown = 0;
					i.range = 0;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[0];
					i.requirements = new BuildingType[1];
					i.requirements[0] = BuildingType.Stronghold;
					i.score = 6;
					i.number = 2;
					i.numberPerSector = 1;
					break;
				case BuildingType.SpiritLodge:
					i.fraction = Fraction.Orcs;
					i.name = "Spirit Lodge";
					i.image = "/Orcs/SpiritLodge.gif";
					i.createImage = "/Orcs/SpiritLodge.gif";
					i.gold = 150;
					i.lumber = 150;
					i.hitpoints = 800;
					i.minutes = 210;
					i.armor = 5;
					i.armorType = ArmorType.Fort;
					i.attackTypeAir = AttackType.None;
					i.attackTypeGround = AttackType.None;
					i.attackAir = 0;
					i.attackGround = 0;
					i.cooldown = 0;
					i.range = 0;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[0];
					i.requirements = new BuildingType[1];
					i.requirements[0] = BuildingType.Stronghold;
					i.score = 6;
					i.number = 2;
					i.numberPerSector = 1;
					break;
				case BuildingType.TaurenTotem:
					i.fraction = Fraction.Orcs;
					i.name = "Tauren Totem";
					i.image = "/Orcs/TaurenTotem.gif";
					i.createImage = "/Orcs/TaurenTotem.gif";
					i.gold = 135;
					i.lumber = 155;
					i.hitpoints = 1200;
					i.minutes = 210;
					i.armor = 5;
					i.armorType = ArmorType.Fort;
					i.attackTypeAir = AttackType.None;
					i.attackTypeGround = AttackType.None;
					i.attackAir = 0;
					i.attackGround = 0;
					i.cooldown = 0;
					i.range = 0;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[0];
					i.requirements = new BuildingType[2];
					i.requirements[0] = BuildingType.Fortress;
					i.requirements[1] = BuildingType.WarMill;
					i.score = 10;
					i.number = 1;
					i.numberPerSector = 1;
					break;
				case BuildingType.VoodooLounge:
					i.fraction = Fraction.Orcs;
					i.name = "Voodoo Lounge";
					i.image = "/Orcs/VoodooLounge.gif";
					i.createImage = "/Orcs/VoodooLounge.gif";
					i.gold = 130;
					i.lumber = 30;
					i.hitpoints = 500;
					i.minutes = 180;
					i.armor = 5;
					i.armorType = ArmorType.Fort;
					i.attackTypeAir = AttackType.None;
					i.attackTypeGround = AttackType.None;
					i.attackAir = 0;
					i.attackGround = 0;
					i.cooldown = 0;
					i.range = 0;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[0];
					i.requirements = new BuildingType[0];
					i.score = 4;
					i.number = 2;
					i.numberPerSector = 1;
					break;
				case BuildingType.HauntedGoldMine:
					i.fraction = Fraction.Undead;
					i.name = "Haunted Gold Mine";
					i.image = "/Undead/HauntedGoldMine.gif";
					i.createImage = "/Undead/HauntedGoldMine.gif";
					i.gold = 255;
					i.lumber = 220;
					i.hitpoints = 800;
					i.minutes = 300;
					i.armor = 5;
					i.armorType = ArmorType.Fort;
					i.attackTypeAir = AttackType.None;
					i.attackTypeGround = AttackType.None;
					i.attackAir = 0;
					i.attackGround = 0;
					i.cooldown = 0;
					i.range = 0;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[0];
					i.requirements = new BuildingType[0];
					i.score = 2;
					i.number = 6;
					i.numberPerSector = 1;
					break;
				case BuildingType.Necropolis:
					i.fraction = Fraction.Undead;
					i.name = "Necropolis";
					i.image = "/Undead/Necropolis.gif";
					i.createImage = "/Undead/Necropolis.gif";
					i.gold = 255;
					i.lumber = 0;
					i.hitpoints = 1500;
					i.minutes = 360;
					i.armor = 5;
					i.armorType = ArmorType.Fort;
					i.attackTypeAir = AttackType.None;
					i.attackTypeGround = AttackType.None;
					i.attackAir = 0;
					i.attackGround = 0;
					i.cooldown = 0;
					i.range = 0;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[1];
					i.upgradesTo[0] = BuildingType.HallsOfTheDead;
					i.requirements = new BuildingType[0];
					i.score = 3;
					i.number = 3;
					i.numberPerSector = 1;
					i.food = 10;
					break;
				case BuildingType.Crypt:
					i.fraction = Fraction.Undead;
					i.name = "Crypt";
					i.image = "/Undead/Crypt.gif";
					i.createImage = "/Undead/Crypt.gif";
					i.gold = 200;
					i.lumber = 50;
					i.hitpoints = 1300;
					i.minutes = 180;
					i.armor = 5;
					i.armorType = ArmorType.Fort;
					i.attackTypeAir = AttackType.None;
					i.attackTypeGround = AttackType.None;
					i.attackAir = 0;
					i.attackGround = 0;
					i.cooldown = 0;
					i.range = 0;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[0];
					i.requirements = new BuildingType[0];
					i.score = 4;
					i.number = 2;
					i.numberPerSector = 1;
					break;
				case BuildingType.Ziggurat:
					i.fraction = Fraction.Undead;
					i.name = "Ziggurat";
					i.image = "/Undead/Ziggurat.gif";
					i.createImage = "/Undead/Ziggurat.gif";
					i.gold = 150;
					i.lumber = 50;
					i.hitpoints = 550;
					i.minutes = 150;
					i.armor = 1;
					i.armorType = ArmorType.Fort;
					i.attackTypeAir = AttackType.None;
					i.attackTypeGround = AttackType.None;
					i.attackAir = 0;
					i.attackGround = 0;
					i.cooldown = 0;
					i.range = 0;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[2];
					i.upgradesTo[0] = BuildingType.NerubianTower;
					i.upgradesTo[1] = BuildingType.SpiritTower;
					i.requirements = new BuildingType[0];
					i.score = 2;
					i.number = 20;
					i.numberPerSector = 20;
					i.food = 10;
					break;
				case BuildingType.AltarOfDarkness:
					i.fraction = Fraction.Undead;
					i.name = "Altar Of Darkness";
					i.image = "/Undead/AltarOfDarkness.gif";
					i.createImage = "/Undead/AltarOfDarkness.gif";
					i.gold = 180;
					i.lumber = 50;
					i.hitpoints = 900;
					i.minutes = 180;
					i.armor = 5;
					i.armorType = ArmorType.Fort;
					i.attackTypeAir = AttackType.None;
					i.attackTypeGround = AttackType.None;
					i.attackAir = 0;
					i.attackGround = 0;
					i.cooldown = 0;
					i.range = 0;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[0];
					i.requirements = new BuildingType[0];
					i.score = 5;
					i.number = 2;
					i.numberPerSector = 1;
					break;
				case BuildingType.Graveyard:
					i.fraction = Fraction.Undead;
					i.name = "Graveyard";
					i.image = "/Undead/Graveyard.gif";
					i.createImage = "/Undead/Graveyard.gif";
					i.gold = 215;
					i.lumber = 0;
					i.hitpoints = 900;
					i.minutes = 240;
					i.armor = 5;
					i.armorType = ArmorType.Fort;
					i.attackTypeAir = AttackType.None;
					i.attackTypeGround = AttackType.None;
					i.attackAir = 0;
					i.attackGround = 0;
					i.cooldown = 0;
					i.range = 0;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[0];
					i.requirements = new BuildingType[0];
					i.score = 5;
					i.number = 2;
					i.numberPerSector = 1;
					break;
				case BuildingType.Slaughterhouse:
					i.fraction = Fraction.Undead;
					i.name = "Slaughterhouse";
					i.image = "/Undead/Slaughterhouse.gif";
					i.createImage = "/Undead/Slaughterhouse.gif";
					i.gold = 140;
					i.lumber = 135;
					i.hitpoints = 1200;
					i.minutes = 180;
					i.armor = 5;
					i.armorType = ArmorType.Fort;
					i.attackTypeAir = AttackType.None;
					i.attackTypeGround = AttackType.None;
					i.attackAir = 0;
					i.attackGround = 0;
					i.cooldown = 0;
					i.range = 0;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[0];
					i.requirements = new BuildingType[2];
					i.requirements[0] = BuildingType.Graveyard;
					i.requirements[1] = BuildingType.HallsOfTheDead;
					i.score = 6;
					i.number = 2;
					i.numberPerSector = 1;
					break;
				case BuildingType.TempleOfTheDamned:
					i.fraction = Fraction.Undead;
					i.name = "Temple Of The Damned";
					i.image = "/Undead/TempleOfTheDamned.gif";
					i.createImage = "/Undead/TempleOfTheDamned.gif";
					i.gold = 155;
					i.lumber = 140;
					i.hitpoints = 1100;
					i.minutes = 180;
					i.armor = 5;
					i.armorType = ArmorType.Fort;
					i.attackTypeAir = AttackType.None;
					i.attackTypeGround = AttackType.None;
					i.attackAir = 0;
					i.attackGround = 0;
					i.cooldown = 0;
					i.range = 0;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[0];
					i.requirements = new BuildingType[2];
					i.requirements[0] = BuildingType.Graveyard;
					i.requirements[1] = BuildingType.HallsOfTheDead;
					i.score = 6;
					i.number = 2;
					i.numberPerSector = 1;
					break;
				case BuildingType.SacrificialPit:
					i.fraction = Fraction.Undead;
					i.name = "Sacrificial Pit";
					i.image = "/Undead/SacrificialPit.gif";
					i.createImage = "/Undead/SacrificialPit.gif";
					i.gold = 75;
					i.lumber = 150;
					i.hitpoints = 900;
					i.minutes = 135;
					i.armor = 5;
					i.armorType = ArmorType.Fort;
					i.attackTypeAir = AttackType.None;
					i.attackTypeGround = AttackType.None;
					i.attackAir = 0;
					i.attackGround = 0;
					i.cooldown = 0;
					i.range = 0;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[0];
					i.requirements = new BuildingType[1];
					i.requirements[0] = BuildingType.HallsOfTheDead;
					i.score = 3;
					i.number = 2;
					i.numberPerSector = 1;
					break;
				case BuildingType.Boneyard:
					i.fraction = Fraction.Undead;
					i.name = "Boneyard";
					i.image = "/Undead/Boneyard.gif";
					i.createImage = "/Undead/Boneyard.gif";
					i.gold = 175;
					i.lumber = 200;
					i.hitpoints = 1500;
					i.minutes = 210;
					i.armor = 5;
					i.armorType = ArmorType.Fort;
					i.attackTypeAir = AttackType.None;
					i.attackTypeGround = AttackType.None;
					i.attackAir = 0;
					i.attackGround = 0;
					i.cooldown = 0;
					i.range = 0;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[0];
					i.requirements = new BuildingType[2];
					i.requirements[0] = BuildingType.SacrificialPit;
					i.requirements[1] = BuildingType.BlackCitadel;
					i.score = 10;
					i.number = 1;
					i.numberPerSector = 1;
					break;
				case BuildingType.TombOfRelics:
					i.fraction = Fraction.Undead;
					i.name = "Tomb Of Relics";
					i.image = "/Undead/TombOfRelics.gif";
					i.createImage = "/Undead/TombOfRelics.gif";
					i.gold = 130;
					i.lumber = 30;
					i.hitpoints = 475;
					i.minutes = 180;
					i.armor = 5;
					i.armorType = ArmorType.Fort;
					i.attackTypeAir = AttackType.None;
					i.attackTypeGround = AttackType.None;
					i.attackAir = 0;
					i.attackGround = 0;
					i.cooldown = 0;
					i.range = 0;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[0];
					i.requirements = new BuildingType[0];
					i.score = 4;
					i.number = 2;
					i.numberPerSector = 1;
					break;
				case BuildingType.TownHall:
					i.fraction = Fraction.Humans;
					i.name = "Town Hall";
					i.image = "/Humans/TownHall.jpg";
					i.createImage = "/Humans/TownHall.jpg";
					i.gold = 385;
					i.lumber = 205;
					i.hitpoints = 1500;
					i.minutes = 540;
					i.armor = 5;
					i.armorType = ArmorType.Fort;
					i.attackTypeAir = AttackType.None;
					i.attackTypeGround = AttackType.None;
					i.attackAir = 0;
					i.attackGround = 0;
					i.cooldown = 0;
					i.range = 0;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[1];
					i.upgradesTo[0] = BuildingType.Keep;
					i.requirements = new BuildingType[0];
					i.score = 3;
					i.number = 3;
					i.numberPerSector = 1;
					i.food = 10;
					break;
				case BuildingType.Keep:
					i.fraction = Fraction.Humans;
					i.name = "Keep";
					i.image = "/Humans/Keep.jpg";
					i.createImage = "/Humans/Keep.jpg";
					i.gold = 320;
					i.lumber = 210;
					i.hitpoints = 2000;
					i.minutes = 420;
					i.armor = 5;
					i.armorType = ArmorType.Fort;
					i.attackTypeAir = AttackType.None;
					i.attackTypeGround = AttackType.None;
					i.attackAir = 0;
					i.attackGround = 0;
					i.cooldown = 0;
					i.range = 0;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[1];
					i.upgradesTo[0] = BuildingType.Castle;
					i.requirements = new BuildingType[0];
					i.score = 7;
					i.number = 2;
					i.numberPerSector = 1;
					i.food = 10;
					i.buildable = false;
					break;
				case BuildingType.Castle:
					i.fraction = Fraction.Humans;
					i.name = "Castle";
					i.image = "/Humans/Castle.jpg";
					i.createImage = "/Humans/Castle.jpg";
					i.gold = 360;
					i.lumber = 210;
					i.hitpoints = 2500;
					i.minutes = 420;
					i.armor = 5;
					i.armorType = ArmorType.Fort;
					i.attackTypeAir = AttackType.None;
					i.attackTypeGround = AttackType.None;
					i.attackAir = 0;
					i.attackGround = 0;
					i.cooldown = 0;
					i.range = 0;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[0];
					i.requirements = new BuildingType[1];
					i.requirements[0] = BuildingType.AltarOfKings;
					i.score = 10;
					i.number = 2;
					i.numberPerSector = 1;
					i.food = 10;
					i.buildable = false;
					break;
				case BuildingType.HumanBarracks:
					i.fraction = Fraction.Humans;
					i.name = "Barracks";
					i.image = "/Humans/Barracks.jpg";
					i.createImage = "/Humans/Barracks.jpg";
					i.gold = 160;
					i.lumber = 60;
					i.hitpoints = 1500;
					i.minutes = 180;
					i.armor = 5;
					i.armorType = ArmorType.Fort;
					i.attackTypeAir = AttackType.None;
					i.attackTypeGround = AttackType.None;
					i.attackAir = 0;
					i.attackGround = 0;
					i.cooldown = 0;
					i.range = 0;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[0];
					i.requirements = new BuildingType[0];
					i.score = 4;
					i.number = 2;
					i.numberPerSector = 1;
					break;
				case BuildingType.Farm:
					i.fraction = Fraction.Humans;
					i.name = "Farm";
					i.image = "/Humans/Farm.jpg";
					i.createImage = "/Humans/Farm.jpg";
					i.gold = 80;
					i.lumber = 20;
					i.hitpoints = 500;
					i.minutes = 105;
					i.armor = 5;
					i.armorType = ArmorType.Fort;
					i.attackTypeAir = AttackType.None;
					i.attackTypeGround = AttackType.None;
					i.attackAir = 0;
					i.attackGround = 0;
					i.cooldown = 0;
					i.range = 0;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[0];
					i.requirements = new BuildingType[0];
					i.score = 1;
					i.number = 40;
					i.numberPerSector = 40;
					i.food = 5;
					break;
				case BuildingType.AltarOfKings:
					i.fraction = Fraction.Humans;
					i.name = "Altar Of Kings";
					i.image = "/Humans/AltarOfKings.jpg";
					i.createImage = "/Humans/AltarOfKings.jpg";
					i.gold = 180;
					i.lumber = 50;
					i.hitpoints = 900;
					i.minutes = 180;
					i.armor = 5;
					i.armorType = ArmorType.Fort;
					i.attackTypeAir = AttackType.None;
					i.attackTypeGround = AttackType.None;
					i.attackAir = 0;
					i.attackGround = 0;
					i.cooldown = 0;
					i.range = 0;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[0];
					i.requirements = new BuildingType[0];
					i.score = 4;
					i.number = 2;
					i.numberPerSector = 1;
					break;
				case BuildingType.LumberMill:
					i.fraction = Fraction.Humans;
					i.name = "Lumber Mill";
					i.image = "/Humans/LumberMill.jpg";
					i.createImage = "/Humans/LumberMill.jpg";
					i.gold = 120;
					i.lumber = 0;
					i.hitpoints = 900;
					i.minutes = 180;
					i.armor = 5;
					i.armorType = ArmorType.Fort;
					i.attackTypeAir = AttackType.None;
					i.attackTypeGround = AttackType.None;
					i.attackAir = 0;
					i.attackGround = 0;
					i.cooldown = 0;
					i.range = 0;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[0];
					i.requirements = new BuildingType[0];
					i.score = 5;
					i.number = 2;
					i.numberPerSector = 1;
					break;
				case BuildingType.ScoutTower:
					i.fraction = Fraction.Humans;
					i.name = "Scout Tower";
					i.image = "/Humans/ScoutTower.jpg";
					i.createImage = "/Humans/ScoutTower.jpg";
					i.gold = 30;
					i.lumber = 20;
					i.hitpoints = 300;
					i.minutes = 75;
					i.armor = 0;
					i.armorType = ArmorType.Light;
					i.attackTypeAir = AttackType.None;
					i.attackTypeGround = AttackType.None;
					i.attackAir = 0;
					i.attackGround = 0;
					i.cooldown = 0;
					i.range = 0;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[3];
					i.upgradesTo[0] = BuildingType.GuardTower;
					i.upgradesTo[1] = BuildingType.CannonTower;
					i.upgradesTo[2] = BuildingType.ArcaneTower;
					i.requirements = new BuildingType[0];
					i.score = 1;
					i.number = 5;
					i.numberPerSector = 5;
					break;
				case BuildingType.Blacksmith:
					i.fraction = Fraction.Humans;
					i.name = "Blacksmith";
					i.image = "/Humans/Blacksmith.jpg";
					i.createImage = "/Humans/Blacksmith.jpg";
					i.gold = 140;
					i.lumber = 60;
					i.hitpoints = 1200;
					i.minutes = 210;
					i.armor = 5;
					i.armorType = ArmorType.Fort;
					i.attackTypeAir = AttackType.None;
					i.attackTypeGround = AttackType.None;
					i.attackAir = 0;
					i.attackGround = 0;
					i.cooldown = 0;
					i.range = 0;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[0];
					i.requirements = new BuildingType[1];
					i.requirements[0] = BuildingType.TownHall;
					i.score = 5;
					i.number = 2;
					i.numberPerSector = 1;
					break;
				case BuildingType.Workshop:
					i.fraction = Fraction.Humans;
					i.name = "Workshop";
					i.image = "/Humans/Workshop.jpg";
					i.createImage = "/Humans/Workshop.jpg";
					i.gold = 140;
					i.lumber = 140;
					i.hitpoints = 1200;
					i.minutes = 180;
					i.armor = 5;
					i.armorType = ArmorType.Fort;
					i.attackTypeAir = AttackType.None;
					i.attackTypeGround = AttackType.None;
					i.attackAir = 0;
					i.attackGround = 0;
					i.cooldown = 0;
					i.range = 0;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[0];
					i.requirements = new BuildingType[2];
					i.requirements[0] = BuildingType.Keep;
					i.requirements[1] = BuildingType.Blacksmith;
					i.score = 6;
					i.number = 2;
					i.numberPerSector = 1;
					break;
				case BuildingType.ArcaneSanctum:
					i.fraction = Fraction.Humans;
					i.name = "Arcane Sanctum";
					i.image = "/Humans/ArcaneSanctum.jpg";
					i.createImage = "/Humans/ArcaneSanctum.jpg";
					i.gold = 150;
					i.lumber = 140;
					i.hitpoints = 1050;
					i.minutes = 210;
					i.armor = 5;
					i.armorType = ArmorType.Fort;
					i.attackTypeAir = AttackType.None;
					i.attackTypeGround = AttackType.None;
					i.attackAir = 0;
					i.attackGround = 0;
					i.cooldown = 0;
					i.range = 0;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[0];
					i.requirements = new BuildingType[1];
					i.requirements[0] = BuildingType.Keep;
					i.score = 6;
					i.number = 2;
					i.numberPerSector = 1;
					break;
				case BuildingType.GryphonAviary:
					i.fraction = Fraction.Humans;
					i.name = "Gryphon Aviary";
					i.image = "/Humans/GryphonAviary.jpg";
					i.createImage = "/Humans/GryphonAviary.jpg";
					i.gold = 140;
					i.lumber = 150;
					i.hitpoints = 1200;
					i.minutes = 225;
					i.armor = 5;
					i.armorType = ArmorType.Fort;
					i.attackTypeAir = AttackType.None;
					i.attackTypeGround = AttackType.None;
					i.attackAir = 0;
					i.attackGround = 0;
					i.cooldown = 0;
					i.range = 0;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[0];
					i.requirements = new BuildingType[0];
					i.requirements = new BuildingType[2];
					i.requirements[0] = BuildingType.LumberMill;
					i.requirements[1] = BuildingType.Castle;
					i.score = 10;
					i.number = 1;
					i.numberPerSector = 1;
					break;
				case BuildingType.ArcaneVault:
					i.fraction = Fraction.Humans;
					i.name = "Arcane Vault";
					i.image = "/Humans/ArcaneVault.jpg";
					i.createImage = "/Humans/ArcaneVault.jpg";
					i.gold = 130;
					i.lumber = 30;
					i.hitpoints = 485;
					i.minutes = 180;
					i.armor = 5;
					i.armorType = ArmorType.Fort;
					i.attackTypeAir = AttackType.None;
					i.attackTypeGround = AttackType.None;
					i.attackAir = 0;
					i.attackGround = 0;
					i.cooldown = 0;
					i.range = 0;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[0];
					i.requirements = new BuildingType[0];
					i.score = 4;
					i.number = 2;
					i.numberPerSector = 1;
					break;
				case BuildingType.Burrow:
					i.fraction = Fraction.Orcs;
					i.name = "Burrow";
					i.image = "/Orcs/Burrow.gif";
					i.createImage = "/Orcs/Burrow.gif";
					i.gold = 160;
					i.lumber = 40;
					i.hitpoints = 600;
					i.minutes = 150;
					i.armor = 5;
					i.armorType = ArmorType.Heavy;
					i.attackTypeAir = AttackType.None;
					i.attackTypeGround = AttackType.None;
					i.attackAir = 25;
					i.attackGround = 25;
					i.cooldown = 2;
					i.range = 70;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[0];
					i.requirements = new BuildingType[0];
					i.score = 2;
					i.number = 20;
					i.numberPerSector = 10;
					i.food = 10;
					break;
				case BuildingType.WatchTower:
					i.fraction = Fraction.Orcs;
					i.name = "Watch Tower";
					i.image = "/Orcs/WatchTower.gif";
					i.createImage = "/Orcs/WatchTower.gif";
					i.gold = 110;
					i.lumber = 80;
					i.hitpoints = 500;
					i.minutes = 165;
					i.armor = 3;
					i.armorType = ArmorType.Heavy;
					i.attackTypeAir = AttackType.Pierce;
					i.attackTypeGround = AttackType.Pierce;
					i.attackAir = 17;
					i.attackGround = 17;
					i.cooldown = 0.6;
					i.range = 80;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[0];
					i.requirements = new BuildingType[1];
					i.requirements[0] = BuildingType.WarMill;
					i.score = 3;
					i.number = 7;
					i.numberPerSector = 3;
					break;
				case BuildingType.GuardTower:
					i.fraction = Fraction.Humans;
					i.name = "Guard Tower";
					i.image = "/Humans/GuardTower.jpg";
					i.createImage = "/Humans/GuardTower.jpg";
					i.gold = 70;
					i.lumber = 50;
					i.hitpoints = 500;
					i.minutes = 150;
					i.armor = 5 / 11;
					i.armorType = ArmorType.Heavy;
					i.attackTypeAir = AttackType.Pierce;
					i.attackTypeGround = AttackType.Pierce;
					i.attackAir = 25;
					i.attackGround = 25;
					i.cooldown = 0.9;
					i.range = 70;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[0];
					i.requirements = new BuildingType[1];
					i.requirements[0] = BuildingType.LumberMill;
					i.score = 3;
					i.number = 3;
					i.numberPerSector = 2;
					i.buildable = false;
					break;
				case BuildingType.CannonTower:
					i.fraction = Fraction.Humans;
					i.name = "Cannon Tower";
					i.image = "/Humans/CannonTower.jpg";
					i.createImage = "/Humans/CannonTower.jpg";
					i.gold = 170;
					i.lumber = 100;
					i.hitpoints = 600;
					i.minutes = 225;
					i.armor = 5 / 11;
					i.armorType = ArmorType.Fort;
					i.attackTypeAir = AttackType.None;
					i.attackTypeGround = AttackType.Siege;
					i.attackAir = 0;
					i.attackGround = 100;
					i.cooldown = 2.5;
					i.range = 80;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[0];
					i.requirements = new BuildingType[1];
					i.requirements[0] = BuildingType.Workshop;
					i.score = 6;
					i.number = 3;
					i.numberPerSector = 2;
					i.buildable = false;
					break;
				case BuildingType.ArcaneTower:
					i.fraction = Fraction.Humans;
					i.name = "Arcane Tower";
					i.image = "/Humans/ArcaneTower.jpg";
					i.createImage = "/Humans/ArcaneTower.jpg";
					i.gold = 70;
					i.lumber = 50;
					i.hitpoints = 500;
					i.minutes = 150;
					i.armor = 5 / 11;
					i.armorType = ArmorType.Heavy;
					i.attackTypeAir = AttackType.Pierce;
					i.attackTypeGround = AttackType.Pierce;
					i.attackAir = 9;
					i.attackGround = 9;
					i.cooldown = 1;
					i.range = 80;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[0];
					i.requirements = new BuildingType[0];
					i.score = 2;
					i.number = 3;
					i.numberPerSector = 2;
					i.bonusAuraRange = 1.1;
					i.bonusAuraAttackGround = 1.1;
					i.malusAuraArmor = 1.1;
					i.buildable = false;
					break;
				case BuildingType.NerubianTower:
					i.fraction = Fraction.Undead;
					i.name = "Nerubian Tower";
					i.image = "/Undead/NerubianTower.gif";
					i.createImage = "/Undead/NerubianTower.gif";
					i.gold = 100;
					i.lumber = 20;
					i.hitpoints = 550;
					i.minutes = 90;
					i.armor = 5;
					i.armorType = ArmorType.Fort;
					i.attackTypeAir = AttackType.Normal;
					i.attackTypeGround = AttackType.Normal;
					i.attackAir = 9;
					i.attackGround = 9;
					i.cooldown = 1;
					i.range = 70;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[0];
					i.requirements = new BuildingType[0];
					i.score = 4;
					i.number = 4;
					i.numberPerSector = 3;
					i.bonusAuraAttackGround = 1.1;
					i.bonusAuraAttackAir = 1.1;
					i.food = 10;
					i.buildable = false;
					break;
				case BuildingType.SpiritTower:
					i.fraction = Fraction.Undead;
					i.name = "Spirit Tower";
					i.image = "/Undead/SpiritTower.gif";
					i.createImage = "/Undead/SpiritTower.gif";
					i.gold = 145;
					i.lumber = 40;
					i.hitpoints = 550;
					i.minutes = 105;
					i.armor = 5;
					i.armorType = ArmorType.Fort;
					i.attackTypeAir = AttackType.Pierce;
					i.attackTypeGround = AttackType.Pierce;
					i.attackAir = 29;
					i.attackGround = 29;
					i.cooldown = 1;
					i.range = 70;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[0];
					i.requirements = new BuildingType[1];
					i.requirements[0] = BuildingType.Graveyard;
					i.score = 2;
					i.number = 4;
					i.numberPerSector = 3;
					i.food = 10;
					i.buildable = false;
					break;
				case BuildingType.HallsOfTheDead:
					i.fraction = Fraction.Undead;
					i.name = "Halls Of The Dead";
					i.image = "/Undead/HallsOfTheDead.gif";
					i.createImage = "/Undead/HallsOfTheDead.gif";
					i.gold = 320;
					i.lumber = 210;
					i.hitpoints = 1750;
					i.minutes = 420;
					i.armor = 5;
					i.armorType = ArmorType.Fort;
					i.attackTypeAir = AttackType.Pierce;
					i.attackTypeGround = AttackType.Pierce;
					i.attackAir = 11;
					i.attackGround = 11;
					i.cooldown = 1;
					i.range = 80;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[1];
					i.upgradesTo[0] = BuildingType.BlackCitadel;
					i.requirements = new BuildingType[0];
					i.score = 7;
					i.number = 2;
					i.numberPerSector = 1;
					i.food = 10;
					i.buildable = false;
					break;
				case BuildingType.BlackCitadel:
					i.fraction = Fraction.Undead;
					i.name = "Black Citadel";
					i.image = "/Undead/BlackCitadel.gif";
					i.createImage = "/Undead/BlackCitadel.gif";
					i.gold = 325;
					i.lumber = 230;
					i.hitpoints = 2000;
					i.minutes = 420;
					i.armor = 5;
					i.armorType = ArmorType.Fort;
					i.attackTypeAir = AttackType.Pierce;
					i.attackTypeGround = AttackType.Pierce;
					i.attackAir = 14;
					i.attackGround = 14;
					i.cooldown = 1;
					i.range = 80;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[0];
					i.requirements = new BuildingType[1];
					i.requirements[0] = BuildingType.AltarOfDarkness;
					i.score = 10;
					i.number = 1;
					i.numberPerSector = 1;
					i.food = 10;
					i.buildable = false;
					break;
				case BuildingType.TreeOfLife:
					i.fraction = Fraction.NightElves;
					i.name = "Tree Of Life";
					i.image = "/NightElves/TreeOfLife.gif";
					i.createImage = "/NightElves/TreeOfLife.gif";
					i.gold = 340;
					i.lumber = 185;
					i.hitpoints = 1300;
					i.minutes = 330;
					i.armor = 2 / 7;
					i.armorType = ArmorType.Fort;
					i.attackTypeAir = AttackType.None;
					i.attackTypeGround = AttackType.Normal;
					i.attackAir = 0;
					i.attackGround = 45;
					i.cooldown = 2.5;
					i.range = 0;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[1];
					i.upgradesTo[0] = BuildingType.TreeOfAges;
					i.requirements = new BuildingType[0];
					i.score = 3;
					i.number = 3;
					i.numberPerSector = 1;
					i.food = 10;
					break;
				case BuildingType.TreeOfAges:
					i.fraction = Fraction.NightElves;
					i.name = "Tree Of Ages";
					i.image = "/NightElves/TreeOfAges.gif";
					i.createImage = "/NightElves/TreeOfAges.gif";
					i.gold = 320;
					i.lumber = 180;
					i.hitpoints = 1700;
					i.minutes = 420;
					i.armor = 2 / 7;
					i.armorType = ArmorType.Fort;
					i.attackTypeAir = AttackType.None;
					i.attackTypeGround = AttackType.Normal;
					i.attackAir = 0;
					i.attackGround = 54;
					i.cooldown = 2.5;
					i.range = 0;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[1];
					i.upgradesTo[0] = BuildingType.TreeOfEternity;
					i.requirements = new BuildingType[0];
					i.score = 7;
					i.number = 2;
					i.numberPerSector = 1;
					i.food = 10;
					i.buildable = false;
					break;
				case BuildingType.TreeOfEternity:
					i.fraction = Fraction.NightElves;
					i.name = "Tree Of Eternity";
					i.image = "/NightElves/TreeOfEternity.gif";
					i.createImage = "/NightElves/TreeOfEternity.gif";
					i.gold = 330;
					i.lumber = 200;
					i.hitpoints = 2000;
					i.minutes = 420;
					i.armor = 2 / 7;
					i.armorType = ArmorType.Fort;
					i.attackTypeAir = AttackType.None;
					i.attackTypeGround = AttackType.Normal;
					i.attackAir = 0;
					i.attackGround = 67;
					i.cooldown = 2.5;
					i.range = 0;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[0];
					i.requirements = new BuildingType[1];
					i.requirements[0] = BuildingType.AltarOfElders;
					i.score = 10;
					i.number = 1;
					i.numberPerSector = 1;
					i.food = 10;
					i.buildable = false;
					break;
				case BuildingType.AncientOfWar:
					i.fraction = Fraction.NightElves;
					i.name = "Ancient Of War";
					i.image = "/NightElves/AncientOfWar.gif";
					i.createImage = "/NightElves/AncientOfWar.gif";
					i.gold = 150;
					i.lumber = 60;
					i.hitpoints = 1000;
					i.minutes = 180;
					i.armor = 2 / 7;
					i.armorType = ArmorType.Fort;
					i.attackTypeAir = AttackType.None;
					i.attackTypeGround = AttackType.Normal;
					i.attackAir = 0;
					i.attackGround = 50;
					i.cooldown = 2.5;
					i.range = 0;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[0];
					i.requirements = new BuildingType[0];
					i.score = 4;
					i.number = 2;
					i.numberPerSector = 1;
					break;
				case BuildingType.AncientOfLore:
					i.fraction = Fraction.NightElves;
					i.name = "Ancient Of Lore";
					i.image = "/NightElves/AncientOfLore.gif";
					i.createImage = "/NightElves/AncientOfLore.gif";
					i.gold = 155;
					i.lumber = 145;
					i.hitpoints = 900;
					i.minutes = 210;
					i.armor = 2 / 7;
					i.armorType = ArmorType.Fort;
					i.attackTypeAir = AttackType.None;
					i.attackTypeGround = AttackType.Normal;
					i.attackAir = 0;
					i.attackGround = 45;
					i.cooldown = 2.5;
					i.range = 0;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[0];
					i.requirements = new BuildingType[2];
					i.requirements[0] = BuildingType.TreeOfAges;
					i.requirements[1] = BuildingType.HuntersHall;
					i.score = 6;
					i.number = 2;
					i.numberPerSector = 1;
					break;
				case BuildingType.AncientOfWind:
					i.fraction = Fraction.NightElves;
					i.name = "Ancient Of Wind";
					i.image = "/NightElves/AncientOfWind.gif";
					i.createImage = "/NightElves/AncientOfWind.gif";
					i.gold = 150;
					i.lumber = 140;
					i.hitpoints = 900;
					i.minutes = 180;
					i.armor = 2 / 7;
					i.armorType = ArmorType.Fort;
					i.attackTypeAir = AttackType.None;
					i.attackTypeGround = AttackType.Normal;
					i.attackAir = 0;
					i.attackGround = 42;
					i.cooldown = 2.5;
					i.range = 0;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[0];
					i.requirements = new BuildingType[1];
					i.requirements[0] = BuildingType.TreeOfAges;
					i.score = 6;
					i.number = 2;
					i.numberPerSector = 1;
					break;
				case BuildingType.AncientProtector:
					i.fraction = Fraction.NightElves;
					i.name = "Ancient Protector";
					i.image = "/NightElves/AncientProtector.gif";
					i.createImage = "/NightElves/AncientProtector.gif";
					i.gold = 135;
					i.lumber = 80;
					i.hitpoints = 600;
					i.minutes = 180;
					i.armor = 1 / 3;
					i.armorType = ArmorType.Fort;
					i.attackTypeAir = AttackType.Pierce;
					i.attackTypeGround = AttackType.Pierce;
					i.attackAir = 49;
					i.attackGround = 49;
					i.cooldown = 2;
					i.range = 70;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[0];
					i.requirements = new BuildingType[1];
					i.requirements[0] = BuildingType.HuntersHall;
					i.score = 5;
					i.number = 6;
					i.numberPerSector = 4;
					break;
				case BuildingType.AncientOfWonders:
					i.fraction = Fraction.NightElves;
					i.name = "Ancient Of Wonders";
					i.image = "/NightElves/AncientOfWonders.gif";
					i.createImage = "/NightElves/AncientOfWonders.gif";
					i.gold = 90;
					i.lumber = 30;
					i.hitpoints = 450;
					i.minutes = 180;
					i.armor = 5;
					i.armorType = ArmorType.Fort;
					i.attackTypeAir = AttackType.None;
					i.attackTypeGround = AttackType.Normal;
					i.attackAir = 0;
					i.attackGround = 23;
					i.cooldown = 2.5;
					i.range = 0;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[0];
					i.requirements = new BuildingType[0];
					i.score = 4;
					i.number = 2;
					i.numberPerSector = 1;
					break;
				case BuildingType.MoonWell:
					i.fraction = Fraction.NightElves;
					i.name = "Moon Well";
					i.image = "/NightElves/MoonWell.gif";
					i.createImage = "/NightElves/MoonWell.gif";
					i.gold = 180;
					i.lumber = 40;
					i.hitpoints = 600;
					i.minutes = 150;
					i.armor = 5;
					i.armorType = ArmorType.Fort;
					i.attackTypeAir = AttackType.None;
					i.attackTypeGround = AttackType.None;
					i.attackAir = 0;
					i.attackGround = 0;
					i.cooldown = 0;
					i.range = 0;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[0];
					i.requirements = new BuildingType[0];
					i.score = 2;
					i.number = 20;
					i.numberPerSector = 20;
					i.food = 10;
					break;
				case BuildingType.AltarOfElders:
					i.fraction = Fraction.NightElves;
					i.name = "Altar Of Elders";
					i.image = "/NightElves/AltarOfElders.gif";
					i.createImage = "/NightElves/AltarOfElders.gif";
					i.gold = 180;
					i.lumber = 50;
					i.hitpoints = 900;
					i.minutes = 180;
					i.armor = 5;
					i.armorType = ArmorType.Fort;
					i.attackTypeAir = AttackType.None;
					i.attackTypeGround = AttackType.None;
					i.attackAir = 0;
					i.attackGround = 0;
					i.cooldown = 0;
					i.range = 0;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[0];
					i.requirements = new BuildingType[0];
					i.score = 5;
					i.number = 2;
					i.numberPerSector = 1;
					break;
				case BuildingType.HuntersHall:
					i.fraction = Fraction.NightElves;
					i.name = "Hunters Hall";
					i.image = "/NightElves/HuntersHall.gif";
					i.createImage = "/NightElves/HuntersHall.gif";
					i.gold = 210;
					i.lumber = 100;
					i.hitpoints = 1100;
					i.minutes = 180;
					i.armor = 5;
					i.armorType = ArmorType.Fort;
					i.attackTypeAir = AttackType.None;
					i.attackTypeGround = AttackType.None;
					i.attackAir = 0;
					i.attackGround = 0;
					i.cooldown = 0;
					i.range = 0;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[0];
					i.requirements = new BuildingType[1];
					i.requirements[0] = BuildingType.TreeOfLife;
					i.score = 4;
					i.number = 2;
					i.numberPerSector = 1;
					break;
				case BuildingType.ChimaeraRoost:
					i.fraction = Fraction.NightElves;
					i.name = "Chimaera Roost";
					i.image = "/NightElves/ChimaeraRoost.gif";
					i.createImage = "/NightElves/ChimaeraRoost.gif";
					i.gold = 140;
					i.lumber = 190;
					i.hitpoints = 1200;
					i.minutes = 240;
					i.armor = 5;
					i.armorType = ArmorType.Fort;
					i.attackTypeAir = AttackType.None;
					i.attackTypeGround = AttackType.None;
					i.attackAir = 0;
					i.attackGround = 0;
					i.cooldown = 0;
					i.range = 0;
					i.visibility = Visibility.Always;
					i.upgradesTo = new BuildingType[0];
					i.requirements = new BuildingType[2];
					i.requirements[0] = BuildingType.AncientOfWind;
					i.requirements[1] = BuildingType.TreeOfEternity;
					i.score = 10;
					i.number = 1;
					i.numberPerSector = 1;
					break;
			}
			infos[t] = i;
		}
		#endregion

		#region " Properties "
		BuildingType type;
		public BuildingType Type {
			get {
				return type;
			}
		}

		int number;
		public int Number {
			get {
				return number;
			}
		}

		int numberPerSector;
		public int NumberPerSector {
			get {
				return numberPerSector;
			}
		}

		BuildingType[] upgradesTo;
		public BuildingType[] UpgradesTo {
			get {
				return upgradesTo;
			}
		}
		#endregion
	}
}